package life.myheart.community.mapper;

import java.util.List;
import life.myheart.community.model.Word;
import life.myheart.community.model.WordExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface WordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word
     *
     * @mbg.generated Sat Apr 11 19:55:17 GMT+08:00 2020
     */
    long countByExample(WordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word
     *
     * @mbg.generated Sat Apr 11 19:55:17 GMT+08:00 2020
     */
    int deleteByExample(WordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word
     *
     * @mbg.generated Sat Apr 11 19:55:17 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word
     *
     * @mbg.generated Sat Apr 11 19:55:17 GMT+08:00 2020
     */
    int insert(Word record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word
     *
     * @mbg.generated Sat Apr 11 19:55:17 GMT+08:00 2020
     */
    int insertSelective(Word record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word
     *
     * @mbg.generated Sat Apr 11 19:55:17 GMT+08:00 2020
     */
    List<Word> selectByExampleWithRowbounds(WordExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word
     *
     * @mbg.generated Sat Apr 11 19:55:17 GMT+08:00 2020
     */
    List<Word> selectByExample(WordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word
     *
     * @mbg.generated Sat Apr 11 19:55:17 GMT+08:00 2020
     */
    Word selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word
     *
     * @mbg.generated Sat Apr 11 19:55:17 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") Word record, @Param("example") WordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word
     *
     * @mbg.generated Sat Apr 11 19:55:17 GMT+08:00 2020
     */
    int updateByExample(@Param("record") Word record, @Param("example") WordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word
     *
     * @mbg.generated Sat Apr 11 19:55:17 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(Word record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word
     *
     * @mbg.generated Sat Apr 11 19:55:17 GMT+08:00 2020
     */
    int updateByPrimaryKey(Word record);
}