package life.myheart.community.model;

public class Tags {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tags.id
     *
     * @mbg.generated Sat Apr 11 19:55:17 GMT+08:00 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tags.tag
     *
     * @mbg.generated Sat Apr 11 19:55:17 GMT+08:00 2020
     */
    private String tag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tags.father
     *
     * @mbg.generated Sat Apr 11 19:55:17 GMT+08:00 2020
     */
    private Long father;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tags.id
     *
     * @return the value of tags.id
     *
     * @mbg.generated Sat Apr 11 19:55:17 GMT+08:00 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tags.id
     *
     * @param id the value for tags.id
     *
     * @mbg.generated Sat Apr 11 19:55:17 GMT+08:00 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tags.tag
     *
     * @return the value of tags.tag
     *
     * @mbg.generated Sat Apr 11 19:55:17 GMT+08:00 2020
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tags.tag
     *
     * @param tag the value for tags.tag
     *
     * @mbg.generated Sat Apr 11 19:55:17 GMT+08:00 2020
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tags.father
     *
     * @return the value of tags.father
     *
     * @mbg.generated Sat Apr 11 19:55:17 GMT+08:00 2020
     */
    public Long getFather() {
        return father;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tags.father
     *
     * @param father the value for tags.father
     *
     * @mbg.generated Sat Apr 11 19:55:17 GMT+08:00 2020
     */
    public void setFather(Long father) {
        this.father = father;
    }
}