package life.myheart.community.model;

public class Word {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word.id
     *
     * @mbg.generated Sat Apr 11 19:55:17 GMT+08:00 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word.sensitive_words
     *
     * @mbg.generated Sat Apr 11 19:55:17 GMT+08:00 2020
     */
    private String sensitiveWords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word.status
     *
     * @mbg.generated Sat Apr 11 19:55:17 GMT+08:00 2020
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word.id
     *
     * @return the value of word.id
     *
     * @mbg.generated Sat Apr 11 19:55:17 GMT+08:00 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word.id
     *
     * @param id the value for word.id
     *
     * @mbg.generated Sat Apr 11 19:55:17 GMT+08:00 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word.sensitive_words
     *
     * @return the value of word.sensitive_words
     *
     * @mbg.generated Sat Apr 11 19:55:17 GMT+08:00 2020
     */
    public String getSensitiveWords() {
        return sensitiveWords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word.sensitive_words
     *
     * @param sensitiveWords the value for word.sensitive_words
     *
     * @mbg.generated Sat Apr 11 19:55:17 GMT+08:00 2020
     */
    public void setSensitiveWords(String sensitiveWords) {
        this.sensitiveWords = sensitiveWords == null ? null : sensitiveWords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word.status
     *
     * @return the value of word.status
     *
     * @mbg.generated Sat Apr 11 19:55:17 GMT+08:00 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word.status
     *
     * @param status the value for word.status
     *
     * @mbg.generated Sat Apr 11 19:55:17 GMT+08:00 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}